[package]
name = "nomad-style"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
cssparser = "0.31"
selectors = "0.25"
markup5ever = "0.12"
markup5ever_rcdom = "0.2"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
