[package]
name = "nomad-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nomad-net = { path = "../nomad-net" }
nomad-html = { path = "../nomad-html" }
nomad-style = { path = "../nomad-style" }
nomad-layout = { path = "../nomad-layout" }
nomad-render = { path = "../nomad-render" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
markup5ever_rcdom = "0.2"
